// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {IPoolManager} from "v4-core/interfaces/IPoolManager.sol";
import {PoolKey} from "v4-core/types/PoolKey.sol";
import {IdentiFIHook} from "../src/IdentiFIHook.sol";
import {SwapParams} from "v4-core/types/PoolOperation.sol";
import {BeforeSwapDelta} from "v4-core/types/BeforeSwapDelta.sol";
import {Currency} from "v4-core/types/Currency.sol";
import {JobberUniversal} from "../src/JobberUniversal.sol";

/**
 * @title IdentiFI Hook Unit Tests
 * @notice Validates signature decoding, length verification, and identity propagation via IMsgSender.
 */
contract IdentiFIHookTest is Test {
    IdentiFIHook hook;
    JobberUniversal jobber; 
    address mockPoolManager;
    address testUser;

    function setUp() public {
        mockPoolManager = makeAddr("mockPoolManager"); 
        testUser = 0x18CE24479089dd1DE74419A5296B2cbcC5ED4AA5; 
        
        // 1. Deploy Jobber Router
        jobber = new JobberUniversal(mockPoolManager);

        // 2. Deploy IdentiFI Hook
        hook = new IdentiFIHook(
            IPoolManager(mockPoolManager), 
            address(0x7a4462add2847DA5063337Cbf60bD2796b7510eb)
        );
        
        // Authorize the Jobber router in the Hook whitelist
        hook.setTrustedRouter(address(jobber), true);

        // Etch code at testUser to prevent interface call failures (for IMsgSender checks)
        vm.etch(testUser, hex"60006000f3"); 
    } 

    
    /**
     * @notice Test: Rejection when hookData has an incorrect length (68 bytes instead of 69).
     */
    function testBeforeSwapWrongSize() public {
        bytes memory wrongSize = new bytes(127); 

        SwapParams memory params = SwapParams({
            zeroForOne: true,
            amountSpecified: -1 ether,
            sqrtPriceLimitX96: 0
        });

        PoolKey memory key = PoolKey({
            currency0: Currency.wrap(address(0)),
            currency1: Currency.wrap(address(0x1234)),
            fee: 3000,
            tickSpacing: 60,
            hooks: hook
        });

        vm.prank(mockPoolManager);
        vm.expectRevert(IdentiFIHook.InvalidHookData.selector);
        hook.beforeSwap(testUser, key, params, wrongSize);
    }

    /**
     * @notice Test: Rejection when signature is invalid (69 bytes of zeros).
     */
    function testBeforeSwapInvalidSignature() public {
        uint256 proofNonce = 1;
        bytes memory hookData = new bytes(128);
        
        // Fill nonce in hookData to bypass the Replay check and reach the signature verification
        assembly {
            mstore(add(hookData, 32), proofNonce)
        }

        // Mock the msgSender() call from Jobber so the Hook retrieves 'testUser'
        vm.mockCall(address(jobber), abi.encodeWithSelector(jobber.msgSender.selector), abi.encode(testUser));

        SwapParams memory params = SwapParams({
            zeroForOne: true,
            amountSpecified: -1 ether,
            sqrtPriceLimitX96: 0
        });

        PoolKey memory key = PoolKey({
            currency0: Currency.wrap(address(0)),
            currency1: Currency.wrap(address(0x1234)),
            fee: 3000,
            tickSpacing: 60,
            hooks: hook
        });

        vm.prank(mockPoolManager);
        vm.expectRevert(IdentiFIHook.InvalidSignature.selector);
        
        // Using correct parameters: sender (Jobber) and hookData
        hook.beforeSwap(address(jobber), key, params, hookData);
    }

    /**
     * @notice Test: Validation using real hookData exported from the Rust module.
     * @dev Confirms the cryptographic bridge between Rust (Frontend) and Solidity (On-chain).
     */
function testValidateRealHookDataFromRust() public view {
    // Hex signature generated by the Rust lib.rs module
    bytes memory realHookData = hex"00000000000000000000000000000000000000000000000000000000c78f2bebeb7e556f3e6c8e21ba844e92e0d41539596022f473a2c5feea1376ce915b601c646679f4bdee76520bce449d6a9b664f2e1ad127918b1b1f25bef0ea511f0f641c00000000000000000000000000000000000000000000000000000000000000";

    // Call the external validation helper
    bool isValid = hook.validateHookData(testUser, realHookData);
    
    assertTrue(isValid, "Signature from Rust should be valid in the Hook");
}

    /**
     * @notice Test: Consistency check for the validateHookData view function.
     */
    function testValidateHookData() public view {
        bytes memory sig = new bytes(128);
        bool isValid = hook.validateHookData(testUser, sig);
        assertFalse(isValid, "Zero signature should return false");

        bytes memory badSize = new bytes(127);
        bool isBad = hook.validateHookData(testUser, badSize);
        assertFalse(isBad, "Incorrect size should return false");
    }

    /**
     * @notice Fuzz Test: Ensures the hook rejects any hookData length that is not exactly 69 bytes.
     * @param _hookData Randomly generated hook data from the fuzzer.
     */
    function testFuzzBeforeSwapInvalidHookDataLength(bytes calldata _hookData) public {
        // Instruct the fuzzer to only test cases where the length is invalid
        vm.assume(_hookData.length != hook.HOOK_DATA_LENGTH()); 

        // Mock identity propagation
        vm.mockCall(address(jobber), abi.encodeWithSelector(jobber.msgSender.selector), abi.encode(testUser));

        PoolKey memory key = PoolKey({
            currency0: Currency.wrap(address(0)),
            currency1: Currency.wrap(address(0x1234)),
            fee: 3000,
            tickSpacing: 60,
            hooks: hook
        });
        SwapParams memory params = SwapParams({
            zeroForOne: true,
            amountSpecified: -1 ether,
            sqrtPriceLimitX96: 0
        });

        vm.prank(mockPoolManager);
        vm.expectRevert(IdentiFIHook.InvalidHookData.selector);
        hook.beforeSwap(address(jobber), key, params, _hookData);
    }
}