// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test, console} from "forge-std/Test.sol";
import {Deployers} from "@uniswap/v4-core/test/utils/Deployers.sol";
import {MockERC20} from "solmate/src/test/utils/mocks/MockERC20.sol";
import {SwapParams, ModifyLiquidityParams} from "v4-core/types/PoolOperation.sol";
import {Currency, CurrencyLibrary} from "v4-core/types/Currency.sol";
import {PoolKey} from "v4-core/types/PoolKey.sol";
import {LiquidityAmounts} from "@uniswap/v4-core/test/utils/LiquidityAmounts.sol";
import {TickMath} from "v4-core/libraries/TickMath.sol";
import {JobberUniversal} from "../src/JobberUniversal.sol";
import {IdentiFIHook} from "../src/IdentiFIHook.sol";
import {BalanceDelta} from "v4-core/types/BalanceDelta.sol";
import {HookMiner} from "@uniswap/v4-periphery/src/utils/HookMiner.sol";
import {Hooks} from "v4-core/libraries/Hooks.sol";

/**
 * @title Test Jobber Universal
 * @notice Integration tests for the JobberUniversal router and IdentiFIHook validation logic.
 * @dev Uses Uniswap v4 core test utilities.
 */
contract TestJobberUniversal is Test, Deployers {
    using CurrencyLibrary for Currency;

    uint256 private IDENTIFI_SIGNER_PRIVATE_KEY;
    // Authorized signer address corresponding to the Rust/Wasm module master key
    address walletownerkey = 0x7a4462add2847DA5063337Cbf60bD2796b7510eb;

    MockERC20 token;
    JobberUniversal jobber;
    IdentiFIHook identiFIHook;
    
    function setUp() public {
        // Initialize Uniswap v4 Manager and peripheral routers
        deployFreshManagerAndRouters();

        // Fund addresses for liquidity and gas
        vm.deal(address(manager), 100 ether);
        vm.deal(address(this), 100 ether);

        // Setup mock token
        token = new MockERC20("Test Token", "TEST", 18);
        token.mint(address(this), 1000 ether);
        token.approve(address(modifyLiquidityRouter), type(uint256).max);
   
        // 1. Mine and Deploy the Hook with the correct BEFORE_SWAP flag
        uint160 flags = uint160(Hooks.BEFORE_SWAP_FLAG);
        (, bytes32 salt) = HookMiner.find(
            address(this),
            flags,
            type(IdentiFIHook).creationCode,
            abi.encode(address(manager), walletownerkey)
        );
        identiFIHook = new IdentiFIHook{salt: salt}(manager, walletownerkey);

        // 2. Deploy the Universal Router
        jobber = new JobberUniversal(address(manager));

        // 3. Whitelist the Router in the Hook to allow identity propagation
        identiFIHook.setTrustedRouter(address(jobber), true);

        // Standard ERC20 approvals for the Pool Manager
        vm.prank(address(jobber));
        token.approve(address(manager), type(uint256).max);

        // 4. Initialize Pool (ETH/TEST)
        (key,) = initPool(Currency.wrap(address(0)), Currency.wrap(address(token)), identiFIHook, 3000, 60, SQRT_PRICE_1_1);
        
        // 5. Add Liquidity to the pool
        modifyLiquidityRouter.modifyLiquidity{value: 10 ether}(
            key,
            ModifyLiquidityParams({
                tickLower: -60,
                tickUpper: 60,
                liquidityDelta: 10 ether,
                salt: bytes32(0)
            }),
            ZERO_BYTES
        );
    }

    /**
     * @notice Test: Successful swap using a valid hookData generated by the Rust/Wasm module.
     */
    function testUniversalSwap() public {
    // Simulated user address
    address user = 0x18CE24479089dd1DE74419A5296B2cbcC5ED4AA5; 
    vm.deal(user, 10 ether); 
    
    uint256 amountToSwap = 0.1 ether;

    // Real hookData (Nonce + ECDSA Signature) generated by the Frontend/Wasm module
    bytes memory realHookData = hex"00000000000000000000000000000000000000000000000000000000c78f2bebeb7e556f3e6c8e21ba844e92e0d41539596022f473a2c5feea1376ce915b601c646679f4bdee76520bce449d6a9b664f2e1ad127918b1b1f25bef0ea511f0f641c00000000000000000000000000000000000000000000000000000000000000";

    // Execute swap through the Jobber router
    vm.prank(user); 
    jobber.settlement{value: amountToSwap}(
        key,
        amountToSwap,
        true,
        0,
        realHookData
    );

    // Verify the user received the tokens from the swap
    assertGt(token.balanceOf(user), 0);
   }

}